### ISSUE TITLE
自制湘语娄邵片邵东方言投稿

### ISSUE THREAD

**Issue by AlfredLouis00** [ayaka14732/awesome-rime#29]
我自制了一个湘语娄邵片邵东方言的输入法，可以收录一下吗
github链接
https://github.com/AlfredLouis00/rime-inputting-method-of-Sautungva
gitee链接
https://gitee.com/alfredlouis0x7/rime-inputting-method-of-Sautungva/tree/master

**Comment by ayaka14732** [comment]
欢迎 pr

**Comment by AlfredLouis00** [comment]
done
