### ISSUE TITLE
增加词库配置建议

### ISSUE THREAD

**Issue by loda13** [ayaka14732/awesome-rime#32]
是否可以增加https://github.com/iDvel/rime-ice

**Comment by ayaka14732** [comment]
目前沒有收錄此類 repo，但是可以討論新增一個小節收錄

**Comment by loda13** [comment]
这边已经提了pr进去，可以考虑一下收录

**Comment by ayaka14732** [comment]
不如這樣吧，新增一個小節叫做「配置」

**Comment by ayaka14732** [comment]
我剛剛新增了一個小節，叫做「配置」 https://github.com/ayaka14732/awesome-rime/commit/4e6471c92bb8cf3b8c74f171bd6a2ae40516ff85
